services:
  drim-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: drim-db
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      TZ: "America/Mexico_City"
    volumes:
      - drim-db-data:/var/opt/mssql
    networks:
      - drim-network
    restart: always

  drim-api:
    container_name: drim-api
    image: datawaresit/drim-back:latest
    ports:
      - "8090:8080"
    depends_on:
      - drim-db
    environment:
      DB_HOST: "drim-db"
      DB_NAME: "DRIM"
      DB_USER: "sa"
      DB_PASSWORD: "${DB_PASSWORD}"
      FRONT_URL: "${FRONT_URL}"
      TZ: "America/Mexico_City"
    networks:
      - drim-network
    restart: always

  pm-api:
    container_name: pm-api
    image: datawaresit/drim-pm:latest
    ports:
      - "8091:8080"
    depends_on:
      - drim-db
    environment:
      DB_HOST: "drim-db"
      DB_NAME: "PM_API"
      DB_USER: "sa"
      DB_PASSWORD: "${DB_PASSWORD}"
      FRONT_URL: "${FRONT_URL}"
      TZ: "America/Mexico_City"
    networks:
      - drim-network
    restart: always

  drim-front:
    container_name: drim-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "${DRIM_API_URL}"
        NEXT_PUBLIC_API_URL2: "${PM_API_URL}"
    ports:
      - "8089:8080"
    depends_on:
      drim-api:
        condition: service_started
      pm-api:
        condition: service_started
    environment:
      NEXT_PUBLIC_API_URL: "${DRIM_API_URL}"
      NEXT_PUBLIC_API_URL2: "${PM_API_URL}"
      TZ: "America/Mexico_City"
    networks:
      - drim-network
    restart: always

volumes:
  drim-db-data:

networks:
  drim-network:
    driver: bridge